const FETCH_PRODUCTS_BEGIN = 'FETCH_HOME_PRODUCTS_BEGIN';
const FETCH_PRODUCTS_FAILURE = 'FETCH_HOME_PRODUCTS_FAILURE';
const FETCH_HOME_PRODUCTS_SUCCESS = 'FETCH_HOME_PRODUCTS_SUCCESS';
const FETCH_SHOP_PRODUCTS_SUCCESS = 'FETCH_SHOP_PRODUCTS_SUCCESS';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const LOAD_MORE_BEGIN = 'LOAD_MORE_BEGIN';
const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE';
const SET_FAVORITE = 'SET_FAVORITE';

export {
    FETCH_PRODUCTS_BEGIN,
    FETCH_HOME_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILURE,
    FETCH_SHOP_PRODUCTS_SUCCESS,
    DELETE_PRODUCT,
    LOAD_MORE_BEGIN,
    LOAD_MORE_SUCCESS,
    LOAD_MORE_FAILURE,
    SET_FAVORITE
};