const CRUD_ADMIN_BEGIN = 'CRUD_ADMIN_BEGIN';
const CRUD_ADMIN_SUCCESS = 'CRUD_ADMIN_SUCCESS';
const CRUD_ADMIN_FAILURE = 'CRUD_ADMIN_FAILURE';
const CLOSE_SUCCESS_MODAL = 'CLOSE_SUCCESS_MODAL';


export {
    CRUD_ADMIN_BEGIN,
    CRUD_ADMIN_SUCCESS,
    CRUD_ADMIN_FAILURE,
    CLOSE_SUCCESS_MODAL,
};