const FETCH_CATEGORIES_BEGIN = 'FETCH_CATEGORIES_BEGIN';
const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_SUBCATEGORIES_SUCCESS = 'FETCH_SUBCATEGORIES_SUCCESS';

export {
    FETCH_CATEGORIES_BEGIN,
    FETCH_CATEGORIES_FAILURE,
    FETCH_CATEGORIES_SUCCESS,
    FETCH_SUBCATEGORIES_SUCCESS,
};