const UPDATE_TYPES = 'UPDATE_TYPES';
const UPDATE_PRICE = 'UPDATE_PRICE';
const CLEAR_FILTERS = 'CLEAR_FILTERS';
const NOT_READY = 'NOT_READY';

export {
    UPDATE_TYPES,
    UPDATE_PRICE,
    CLEAR_FILTERS,
    NOT_READY
};