const USER_AUTH_BEGIN = 'USER_AUTH_BEGIN';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGIN = 'USER_LOGIN';

export {
    USER_AUTH_BEGIN,
    USER_AUTH_SUCCESS,
    USER_AUTH_FAILURE,
    USER_LOGOUT,
    USER_LOGIN,
};