const FETCH_SINGLE_PRODUCT_BEGIN = 'FETCH_SINGLE_PRODUCT_BEGIN';
const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS';
const FETCH_SINGLE_PRODUCT_FAILURE = 'FETCH_SINGLE_PRODUCT_FAILURE';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';


export {
    FETCH_SINGLE_PRODUCT_BEGIN,
    FETCH_SINGLE_PRODUCT_SUCCESS,
    FETCH_SINGLE_PRODUCT_FAILURE,
    UPDATE_PRODUCT
}