const CREATE_ORDER = "CREATE_ORDER";

const SET_ORDERS = 'SET_ORDERS';
const BEGIN_LOAD_ORDER = 'BEGIN_LOAD_ORDER';
const FAILURE_LOAD_ORDER = 'FAILURE_LOAD_ORDER';

export {
    CREATE_ORDER,
    SET_ORDERS,
    BEGIN_LOAD_ORDER,
    FAILURE_LOAD_ORDER
};